In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import SimpleExpSmoothing

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Project Finance.xlsx to Project Finance.xlsx

In [ ]:
df = pd.read_excel('Project Finance.xlsx', sheet_name='Forecasting')

In [ ]:
df.head()

  Forecasting  Monthly Revenue
0  2013-09-01     6.117184e+06
1  2013-10-01     1.118875e+07
2  2013-11-01     7.630027e+06
3  2013-12-01     6.497387e+06
4  2014-01-01     8.236148e+06

In [ ]:
df['Forecasting'] = pd.to_datetime(df['Forecasting'], errors='coerce')
df.set_index('Forecasting', inplace=True)

In [ ]:
df.head()

             Monthly Revenue
Forecasting
2013-09-01      6.117184e+06
2013-10-01      1.118875e+07
2013-11-01      7.630027e+06
2013-12-01      6.497387e+06
2014-01-01      8.236148e+06

In [ ]:
df = df.asfreq('MS')

In [ ]:
df.head()

             Monthly Revenue
Forecasting
2013-09-01      6.117184e+06
2013-10-01      1.118875e+07
2013-11-01      7.630027e+06
2013-12-01      6.497387e+06
2014-01-01      8.236148e+06

In [ ]:
target_data = df['Monthly Revenue']

In [ ]:
model = SimpleExpSmoothing(target_data, initialization_method='estimated')
model_fit = model.fit(optimized=True)

In [ ]:
print(f"Nilai Alpha optimal: {model_fit.model.params['smoothing_level']}")

Nilai Alpha optimal: 1.4901161193847656e-08

In [ ]:
forecast_resault = model_fit.forecast(steps=12)
print(forecast_resault)

2015-01-01    8.399064e+06
2015-02-01    8.399064e+06
2015-03-01    8.399064e+06
2015-04-01    8.399064e+06
2015-05-01    8.399064e+06
2015-06-01    8.399064e+06
2015-07-01    8.399064e+06
2015-08-01    8.399064e+06
2015-09-01    8.399064e+06
2015-10-01    8.399064e+06
2015-11-01    8.399064e+06
2015-12-01    8.399064e+06
Freq: MS, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error

In [ ]:
jumlah_data = 12
train_data = target_data.iloc[:-jumlah_data]
test_data = target_data.iloc[-jumlah_data:]

In [ ]:
model = SimpleExpSmoothing(train_data, initialization_method='estimated')
model_fit = model.fit(optimized=True)

In [ ]:
predictions = model_fit.forecast(steps=len(test_data))

In [ ]:
rmse = np.sqrt(mean_squared_error(test_data, predictions))
mape = mean_absolute_percentage_error(test_data, predictions)*100

In [ ]:
print(f"Nilai RMSE: {rmse:.2f}")
print(f"Nilai MAPE: {mape:.2f}%")

Nilai RMSE: 2502188.26
Nilai MAPE: 18.52%